<?php
$con=mysqli_connect("localhost","root","","controldeflotilla") or die (mysqli_error());

$numero=$_POST['numero'];
$conductor=$_POST['conductor'];
$vehiculo=$_POST['vehiculo'];
$kilometraje=$_POST['kilometraje'];
$fecha_revision=$_POST['fecha_revision'];
$hora_revision=$_POST['hora_revision'];
$nivel_gasolina=$_POST['nivel_gasolina'];
$luces_delanteras_baja=$_POST['luces_delanteras_baja'];
$luces_delanteras_alta=$_POST['luces_delanteras_alta'];
$luces_traseras=$_POST['luces_traseras'];
$luces_freno=$_POST['luces_freno'];
$luces_cruce_delantera=$_POST['luces_cruce_delantera'];
$luces_cruce_trasera=$_POST['luces_cruce_trasera'];
$intermitentes_delanteras=$_POST['intermitentes_delanteras'];
$intermitentes_trasera=$_POST['intermitentes_trasera'];
$aceite_transmision=$_POST['aceite_transmision'];
$aceite_motor=$_POST['aceite_motor'];
$aceite_direccion=$_POST['aceite_direccion'];
$refrigerante=$_POST['refrigerante'];
$radiador=$_POST['radiador'];
$liga_freno=$_POST['liga_freno'];
$indicador_combustible=$_POST['indicador_combustible'];
$indicador_temperatura=$_POST['indicador_temperatura'];
$indicador_presion=$_POST['indicador_presion'];
$horometro=$_POST['horometro'];
$tacometro=$_POST['tacometro'];
$velocimetro=$_POST['velocimetro'];
$bocina=$_POST['bocina'];
$alarma=$_POST['alarma'];
$parabrisas=$_POST['parabrisas'];
$gato_hidraulico=$_POST['gato_hidraulico'];
$estado_llantas=$_POST['estado_llantas'];
$retrovisores=$_POST['retrovisores'];
$vidrio_delantero=$_POST['vidrio_delantero'];
$vidrio_trasero=$_POST['vidrio_trasero'];
$vidrio_lateral_delantero=$_POST['vidrio_lateral_delantero'];
$vidrio_lateral_trasero=$_POST['vidrio_lateral_trasero'];
$direccion=$_POST['direccion'];
$suspension_delantera=$_POST['suspension_delantera'];
$suspension_trasera=$_POST['suspension_trasera'];
$pintura=$_POST['pintura'];
$limpieza=$_POST['limpieza'];
$licencia=$_POST['licencia'];
$poliza=$_POST['poliza'];
$tarjeta_circulacion=$_POST['tarjeta_circulacion'];
$placas=$_POST['placas'];
$codigo_bateria=$_POST['codigo_bateria'];
$observaciones=$_POST['observaciones'];


$insert=" INSERT INTO checklist_mtto(num_checklist, conductor, vehiculo, kilometraje, fecha_revision, hora_revision, nivel_gasolina, luces_delanteras_bajas, luces_delanteras_alta, luces_traseras, luces_freno, luces_cruce_delantera, luces_cruce_trasera, intermitentes_delanteras, intermitentes_trasera, aceite_transmision, aceite_motor, aceite_direccion, refrigerante, radiador, liga_freno, indicador_combustible, indicador_temperatura, indicador_presion, horometro, tacometro, velocimetro, bocina, alarma, limpia_parabrisas, gato_hidraulico, neumaticos, retrovisores, vidrio_delantero, vidrio_trasero, vidrio_lateral_delantero, vidrio_lateral_trasero, direccion, suspension_delantera, suspension_trasera, pintura, limpieza, licencia, poliza, tarjeta_circulacion, placas, codigo_bateria, observaciones) VALUES ('$numero',
'$conductor',
'$vehiculo', 
'$kilometraje',
'$fecha_revision',
'$hora_revision',
'$nivel_gasolina',
'$luces_delanteras_baja',
'$luces_delanteras_alta',
'$luces_traseras',
'$luces_freno',
'$luces_cruce_delantera',
'$luces_cruce_trasera',
'$intermitentes_delanteras',
'$intermitentes_trasera',
'$aceite_transmision',
'$aceite_motor',
'$aceite_direccion',
'$refrigerante',
'$radiador',
'$liga_freno',
'$indicador_combustible',
'$indicador_temperatura',
'$indicador_presion',
'$horometro',
'$tacometro',
'$velocimetro',
'$bocina',
'$alarma',
'$parabrisas',
'$gato_hidraulico',
'$estado_llantas',
'$retrovisores',
'$vidrio_delantero',
'$vidrio_trasero',
'$vidrio_lateral_delantero',
'$vidrio_lateral_trasero',
'$direccion',
'$suspension_delantera',
'$suspension_trasera',
'$pintura',
'$limpieza',
'$licencia',
'$poliza',
'$tarjeta_circulacion',
'$placas',
'$codigo_bateria',
'$observaciones'
)";
mysqli_query($con,$insert) or die ("Problemas al insertar".mysqli_error());
mysqli_close($con);
?>

